# Generated by Django 4.2.2 on 2023-06-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('birth_date', models.CharField(max_length=20)),
                ('birth_time', models.CharField(max_length=20)),
                ('birth_place', models.CharField(max_length=255)),
                ('sun', models.CharField(max_length=15)),
                ('moon', models.CharField(max_length=15)),
                ('mercury', models.CharField(max_length=15)),
                ('venus', models.CharField(max_length=15)),
                ('mars', models.CharField(max_length=15)),
                ('jupiter', models.CharField(max_length=15)),
                ('saturn', models.CharField(max_length=15)),
            ],
        ),
    ]
