# Generated by Django 4.2.2 on 2023-06-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='moon_rec',
            field=models.TextField(default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='sun_rec',
            field=models.TextField(default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='true_node_rec',
            field=models.TextField(default='-', max_length=500),
            preserve_default=False,
        ),
    ]
