# Generated by Django 4.2.2 on 2023-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_moon_rec_client_sun_rec_client_true_node_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rising',
            field=models.CharField(default='-', max_length=15),
            preserve_default=False,
        ),
    ]
