# Generated by Django 4.2.2 on 2023-06-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_rising'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='icon',
            field=models.FileField(default='-', upload_to='Users/ovycl/'),
            preserve_default=False,
        ),
    ]
