# Generated by Django 4.2.2 on 2023-06-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_client_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='icon',
        ),
    ]
