# Generated by Django 4.2.2 on 2023-06-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_client_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='icon',
            field=models.FileField(default='-', upload_to='C:/Users/ovycl/constellate/constellatebackend/'),
            preserve_default=False,
        ),
    ]
