# Generated by Django 4.2.2 on 2023-06-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_client_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='icon',
        ),
        migrations.AddField(
            model_name='client',
            name='svg_content',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
